// Code generated by "stringer -type=precomputeType"; DO NOT EDIT.

package backend

import "strconv"

const _precomputeType_name = "notKnownAtCompileTimeintegerpointerRelativeToStackBasepointerRelativeToVar"

var _precomputeType_index = [...]uint8{0, 21, 28, 54, 74}

func (i precomputeType) String() string {
	if i < 0 || i >= precomputeType(len(_precomputeType_index)-1) {
		return "precomputeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _precomputeType_name[_precomputeType_index[i]:_precomputeType_index[i+1]]
}
