// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package parsing

import "strconv"

const _Operator_name = "DotStarMinusPlusRangeDivideCallAssignDeclarePlusEqualMinusEqualLesserLesserEqualGreaterGreaterEqualDoubleEqualBangEqualLogicalAndLogicalOrLogicalNotConstDeclareDereferenceAddressOfArrayAccess"

var _Operator_index = [...]uint8{0, 3, 7, 12, 16, 21, 27, 31, 37, 44, 53, 63, 69, 80, 87, 99, 110, 119, 129, 138, 148, 160, 171, 180, 191}

func (i Operator) String() string {
	i -= 1
	if i < 0 || i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
