// Code generated by "stringer -type=Operator"; DO NOT EDIT

package parsing

import "fmt"

const _Operator_name = "DotStarMinusPlusRangeDivideCallAssignDeclareLesserLesserEqualGreaterGreaterEqualDoubleEqualConstDeclareDereferenceAddressOf"

var _Operator_index = [...]uint8{0, 3, 7, 12, 16, 21, 27, 31, 37, 44, 50, 61, 68, 80, 91, 103, 114, 123}

func (i Operator) String() string {
	i -= 1
	if i < 0 || i >= Operator(len(_Operator_index)-1) {
		return fmt.Sprintf("Operator(%d)", i+1)
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
