// Code generated by "stringer -type=ComparisonMethod"; DO NOT EDIT.

package ir

import "strconv"

const _ComparisonMethod_name = "LesserGreaterGreaterOrEqualLesserOrEqualAreEqualNotEqual"

var _ComparisonMethod_index = [...]uint8{0, 6, 13, 27, 40, 48, 56}

func (i ComparisonMethod) String() string {
	if i < 0 || i >= ComparisonMethod(len(_ComparisonMethod_index)-1) {
		return "ComparisonMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComparisonMethod_name[_ComparisonMethod_index[i]:_ComparisonMethod_index[i+1]]
}
