// Code generated by "stringer -type=InstType"; DO NOT EDIT

package ir

import "fmt"

const _InstType_name = "ZeroVarInstructionsTranscludeJumpStartProcEndProcLabelUnaryInstructionsAssignImmIncrementDecrementJumpIfFalseCallBinaryInstructionsSubAssignAddMultDivTakeAddressArrayToPointerIndirectWriteIndirectLoadStructMemberPtrLoadStructMemberCompare"

var _InstType_index = [...]uint8{0, 19, 29, 33, 42, 49, 54, 71, 80, 89, 98, 109, 113, 131, 134, 140, 143, 147, 150, 161, 175, 188, 200, 215, 231, 238}

func (i InstType) String() string {
	if i < 0 || i >= InstType(len(_InstType_index)-1) {
		return fmt.Sprintf("InstType(%d)", i)
	}
	return _InstType_name[_InstType_index[i]:_InstType_index[i+1]]
}
