// Code generated by "stringer -type=InstType"; DO NOT EDIT.

package ir

import "strconv"

const _InstType_name = "ZeroVarInstructionsReturnTranscludeJumpStartProcEndProcLabelOutsideLoopMutationsMutateOnlyInstructionsCallAssignImmIncrementDecrementReadOnlyInstructionsJumpIfFalseJumpIfTrueCompareReadAndMutateInstructionsAddSubMultDivAssignTakeAddressArrayToPointerIndirectWriteIndirectLoadStructMemberPtrPeelStructNotAndOr"

var _InstType_index = [...]uint16{0, 19, 25, 35, 39, 48, 55, 60, 80, 102, 106, 115, 124, 133, 153, 164, 174, 181, 206, 209, 212, 216, 219, 225, 236, 250, 263, 275, 290, 300, 303, 306, 308}

func (i InstType) String() string {
	if i < 0 || i >= InstType(len(_InstType_index)-1) {
		return "InstType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InstType_name[_InstType_index[i]:_InstType_index[i+1]]
}
