// Code generated by "stringer -type=Operator"; DO NOT EDIT

package parser

import "fmt"

const _Operator_name = "DotStarMinusPlusDivideCallAssignDeclareDereference"

var _Operator_index = [...]uint8{0, 3, 7, 12, 16, 22, 26, 32, 39, 50}

func (i Operator) String() string {
	i -= 1
	if i < 0 || i >= Operator(len(_Operator_index)-1) {
		return fmt.Sprintf("Operator(%d)", i+1)
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
